### PR TITLE
[WIP] Update Windows build script to support qt5

### PR DESCRIPTION
**Pull request by jamesobutler**
@jcfr This is a work in progress to update `qt-easy-build` with support for qt5.

My branch 5.8.0 is designed to include support for qt5 (5.8.0) and qt4 (4.8.7) instead of creating a separate branch for just qt5 build code. This is done with a new argument being included in the powershell command that specifies qtVersion 4 or 5.

### Unknowns:

- Pick a new version of OpenSSL to use because 1.0.1 is out of support. 
From [OpenSSL](https://www.openssl.org/source/):
> The latest stable version is the 1.1.0 series of releases. Also available is the 1.0.2 series. This is also our Long Term Support (LTS) version (support will be provided until 31st December 2019). The 0.9.8, 1.0.0 and 1.0.1 versions are now out of support and should not be used.
- Or support multiple versions of OpenSSL and transition qt4 builds to 1.0.2 series & qt5 builds to 1.1.0 series.
- Best choice of argument flags when configuring qt5 since they are different than qt4 flags

### Missing:

- links to precompiled packages of openssl by Kitware

### Other Notes
Support for msvc2017 was included because qt5.8.0 src includes 
`..\qtbase\mkspecs\win32-msvc2017\qmake.conf`

### CODE REVIEW

**Comment by jcfr** [comment]
Outstanding :+1: 

> 1.0.2 series

For now, I guess we could use this version for both Qt4 and Qt5 (assuming it is supported by Qt5)

> links to precompiled packages of openssl by Kitware

Here is the script allowing to build OpenSSL package, it would have to be updated to support build of OpenSSL  (1.0.2 and/or 1.1.0) . See https://gist.github.com/jcfr/6030240#gistcomment-1541144

**Comment by jcfr** [comment]
xref #15

**Comment by jcfr** [comment]
Moving forward, I suggest we create the branch `4.8.7-5.8.0`

**Comment by jamesobutler** [comment]
I updated the script allowing to build OpenSSL package to support the build of 1.0.2k. See https://gist.github.com/jamesobutler/f29a8edfe70cbdf7c3d94d25c20e1dce

@jcfr The script appears to run correctly and connects to midas for upload. However, I don't see any new items uploaded on the server. Is there an approval process for uploading?
UPDATE: Uploaded items to personal folder manually. I don't have write access to openssl community folder.

**Comment by jamesobutler** [comment]
Since I don't have VS 2010 or 2008, I did not precompile openssl 1.0.2k with those platforms.  I commented out support for 2010 and 2008 so Qt4 can be built with VS2015/13/12 and Qt5 can be built with VS2017/15/13.

Is it ok to drop support for VS 2010 and 2008?

**Comment by jcfr** [comment]
Thanks @jamesobutler , I will have a look later this week and integrate :+1:

**Comment by jcfr** [comment]
>  Is there an approval process for uploading?

Since we currently do not allow third party to upload binaries into packages.kitware.com, I will look into re-generating the binaries using the updated script.

> Is it ok to drop support for VS 2010 and 2008?

For Qt5 it definitively makes sense to drop them.

For Qt4, we still some older project relying on VS2008 ... that said, I will take care of regenerating OpenSSL archives if needs to be

**Comment by jcfr** [comment]
@jamesobutler Thanks again for moving this forward. :+1:  We will soon push this forward and use it as a base to build Slicer proper. See https://www.slicer.org/wiki/Documentation/Labs/Qt5

**Comment by jcfr** [comment]
@jamesobutler Should we close this one? Or is there anything we should bring into `5.15.1` branch ?

**Comment by jamesobutler** [comment]
This is quite out-of-date, so it can be closed. What this has that `5.15.1` doesn't have is some build support on Windows. There is some auto-download of build dependencies that might be a little too overbearing such as downloading Python temporarily to use during the process. Not sure if the development is worth it.  In the context of Slicer, downloading Qt binaries has been working fine. Also Qt 6 is a CMake based build system so this build script would only be of use for those still using Qt 5.

**Comment by jcfr** [comment]
Makes sense. Thanks for the feedback

I guess we could probably completely remove the windows build support and add a note to the README ?

**Comment by jamesobutler** [comment]
Yes, I would agree those changes would improve the understanding about the current status of build support for Windows.

**Comment by jamesobutler** [comment]
Superseded by https://github.com/jcfr/qt-easy-build/pull/45

**Pull request closed without merging**
