### PR TITLE
Added notes for error prevention: No quotes in Windows %PATH%.

### PR DESCRIPTION
**Pull request by dennis2society**
This could also be a "Prerequisite". For now I have put the information into the "Notes" section.
Let me know if I should move it to the Prerequisites section.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the PR :+1: 

I tweaked a little and published my proposed change in #21  If that looks good to you, I will integrate.

Otherwise, I suggest we don't had that section as it is. Do you have more details about the error leading to the addition of this:

```
 +* You might have to add the VS\VC\bin folder to your environment's PATH to let the VS command prompt know about nmake.exe
 +  (i.e. C:\Program Files (x86)\Microsoft Visual Studio XX.0\VC\bin )
```

**Comment by dennis2society** [comment]
I have done some more testing on other machines and there it was not necessary to add VS/VC/bin to the path. On the first machine adding this to my path probably helped when there were still some quotes in the path variable and it just ran into the quotes error later. During the later tests I had first removed the quotes and nmake was found without any problems.
I would omit this line for now.

**Comment by jcfr** [comment]
Thanks for testing and providing feedback :+1:  

Will integrate the PR.

**Comment by jcfr** [comment]
Closing this PR. 

Changes integrated in https://github.com/jcfr/qt-easy-build/commit/71e0367a7c513bb34204e2d1bc78c346fbf6a615

**Pull request closed without merging**
